name: default

on:
  push:
    branches: [ "master" ]

jobs:
  default:
    runs-on: self-hosted
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"

      - name: Run python
        run: python -c "import datetime; print(datetime.datetime.now().isoformat())"

      - name: Run docker compose
        run: docker compose -f docker-compose.yml up

      - name: Tear down docker containers
        run: docker compose -f docker-compose.yml down
