name: pull_request_comment

on:
  pull_request:
    branches: [ "master" ]

jobs:
  pull_request_comment:
    runs-on: self-hosted
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello from the workflow'
            })
